spring.profiles.active: h2
# Spring Boot Multipart Limits
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=55MB

# Tomcat Server Limits
server.tomcat.max-http-form-post-size=55MB
server.tomcat.max-swallow-size=60MB